#pragma config(Sensor, port3,	 Main_Gyro,			 sensorVexIQ_Gyro)
#pragma config(Sensor, port4,	 LED,						 sensorVexIQ_LED)
#pragma config(Motor,	 motor1,					Left,					 tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,	 motor6,					Right,				 tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,	 motor10,					ArmRight,			 tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,	 motor11,					ArmLeft,			 tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//


void driveDistance(float distance) {
	float MoveDistanceRotations=distance/200;
	setMotorTarget(ArmLeft, MoveDistanceRotations, 100);
	setMotorTarget(ArmRight, MoveDistanceRotations, 100);
};

task main()
{
	driveDistance(500);
};
