#pragma config(Sensor, port2,  ArmBottomBumper, sensorVexIQ_Touch)
#pragma config(Sensor, port3,  Main_Gyro,      sensorVexIQ_Gyro)
#pragma config(Sensor, port4,  LED,            sensorVexIQ_LED)
#pragma config(Sensor, port5,  ArmTopBumper,   sensorVexIQ_Touch)
#pragma config(Sensor, port7,  LeftColor,      sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port8,  MidColor,       sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  RightColor,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, FrontUltra,     sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          Left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          Right,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         ArmRight,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         ArmLeft,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int placeHubSequenceState;
int HeightIndex;

void placeHubSequence() {

	static int LastState;
	bool P1;

	if (placeHubSequenceState !=LastState) {
		P1 = true;
		LastState = PlaceHubSequenceState;
	}
	else {
		P1 = false;
	};

	switch(placeHubSequenceState) {

	case 1:
		if (HeightIndex==3 && getJoystickValue(BtnLUp)==1) {
placeHubSequence =2
		}
		break;


	case 2:
	HeightIndex = 2
	if (getMotorZeroVelocity(arm)) {
placeHubSequenceState=3;
}

	break;

	case 3:


	break;
	}



	task main()
	{
		while(1) {

			PlaceHubSequence();

		};
	};
